### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [MPSVerlag/prj-rev-bwfs-dasmoto#6]
https://github.com/MPSVerlag/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%60s%20Arts%20%26%20Crafts/resources/style.css#L13-L30

You're repeating the majority of the styles in these CSS rules. Consolidate them into a more general selector to remove repetition.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

Consider using the universal selector `*` instead of listing out every single tag that needs the default font.

```css
* {
  font-family: Helvetica;
}
```
